create table learning_history
(
    id                      bigint       NOT NULL generated by default as identity,
    member_id              bigint       NOT NULL,
    profile_id              bigint       NOT NULL,
    content_id             bigint       NOT NULL,
    content_type           varchar(50)  NOT NULL,
    act_type                varchar(50)  NOT NULL,
    act_id                  bigint       NOT NULL,
    learning_history_type     varchar(50)  NOT NULL,
    learning_time           integer      not null default 0,
    created_at              timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP (6),
    primary key (id)
);