spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:gadb
    username: sa
    password:

  h2:
    console:
      enabled: true

jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
  database-platform: org.hibernate.dialect.PostgreSQLDialect
#  ??? flyway ?? ??? ??? ?? table ??? migration ???, dummy data ??? data ??? ??? ? ???.
#  flyway-locations:
#    - dataSourceName: lmsDbDataSource
#      locations:
#        - classpath:db/migration
#        - classpath:db/data