spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    gadb:
      driver-class-name: org.postgresql.Driver
      auto-commit: false
      connection-timeout: 3000
      max-lifetime: 50000
      pool-name: HikariCP-Writer

---
spring:
  config.activate.on-profile: local
  datasource:
    gadb:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:gadb;INIT=create domain if not exists oid as blob;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username: sa
      password:
      initialization-mode: always
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
